services:
  - type: web
    name: phantasy-app
    env: node
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase: neon-db # if using Render database, otherwise fill manually
      - key: SESSION_SECRET
        value: "IVqgmQdqjqGqyQsyWGs48tfhXxApJSSp+WAlDLTrmQI3WZx1Z3ldDcBpRBSoUydLlGR+7hIJ7Y3165wMqUVp8Q=="
      - key: NODE_ENV
        value: "production"
