services:
  - type: web
    name: phantasy-app
    env: node
    branch: main
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    plan: free
    nodeVersion: 20.11.1
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: neon-db
          property: connectionString
