services:
  - type: web
    name: phantasy
    env: node
    plan: free  # change to 'starter' or 'standard' if you need more resources
    branch: main
    buildCommand: |
      npm run install-all
      npm run build-all
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: <YOUR_DATABASE_URL>
      - key: SESSION_SECRET
        value: <YOUR_SESSION_SECRET>
      - key: PORT
        value: 10000
